# Generated by Django 3.0.6 on 2020-05-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministry',
            old_name='general_address',
            new_name='GeneralAddress',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='member_address',
            new_name='MemberAddress',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('GeneralAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.GeneralAddress')),
                ('MemberAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.MemberAddress')),
                ('Ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Ministry')),
            ],
        ),
    ]
