# Generated by Django 3.0.5 on 2020-05-03 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),  # noqa: E501
            preserve_default=False,
        ),
    ]
