# Generated by Django 3.0.5 on 2020-05-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_ministry_age_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='age_nickname',
            field=models.CharField(default='Everyone', max_length=50),
        ),
    ]
