# Generated by Django 3.0.5 on 2020-05-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200504_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='user_id',
            new_name='UserProfile',
        ),
    ]
