# Generated by Django 3.0.5 on 2020-05-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200508_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='age_lower_bounds',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='age_nickname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='age_upper_bounds',
            field=models.IntegerField(default=None),
        ),
    ]
