# Generated by Django 3.0.5 on 2020-05-04 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200504_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number_type',
            field=models.CharField(default='Cell', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(default='Home', max_length=100)),
                ('address_line_one', models.CharField(max_length=100)),
                ('address_line_two', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
